framework:
    cache:
        app: cache.adapter.filesystem
        pools:
            nonceCache:
                adapters: cache.adapter.apcu
            sessionCache:
                adapters: cache.adapter.apcu
            requestCache:
                adapters: cache.adapter.apcu
            sessionStorage:
                adapters: cache.adapter.filesystem
            requestStorage:
                adapters: cache.adapter.filesystem

        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: digitaladapt/preauth
