framework:
    rate_limiter:
        burst:
            policy: 'sliding_window'
            limit: '%env(int:BURST_COUNT)%'
            interval: '%env(int:BURST_TIME)% seconds'
            cache_pool: 'rateLimitCache'
        upper:
            policy: 'sliding_window'
            limit: '%env(int:UPPER_COUNT)%'
            interval: '%env(int:UPPER_TIME)% seconds'
            cache_pool: 'rateLimitCache'
        login_limiter:
            policy: compound
            limiters: [burst, upper]

        public_burst:
            policy: 'sliding_window'
            limit: '%env(int:PUBLIC_BURST_COUNT)%'
            interval: '%env(int:PUBLIC_BURST_TIME)% seconds'
            cache_pool: 'publicRateLimitCache'
        public_upper:
            policy: 'sliding_window'
            limit: '%env(int:PUBLIC_UPPER_COUNT)%'
            interval: '%env(int:PUBLIC_UPPER_TIME)% seconds'
            cache_pool: 'publicRateLimitCache'
        public_limiter:
            policy: compound
            limiters: [public_burst, public_upper]
