services:
  preauth:
    env_file:
      # rename "example.env" to ".env", edit as needed
      # strongly recommend setting TOTP_URI, if not provided the app
      # will generate one for you, please copy it into your .env file
      - .env
    expose:
      - 80
    image: digitaladapt/preauth:latest
    restart: unless-stopped
    # if you wish to set the user, you must make sure that the user
    # can write to /config and /data within the container
    #user: <uid>:<gid>
    volumes:
      - preauth-config:/config
      - preauth-data:/data

volumes:
  preauth-config:
  preauth-data:

